// 
for (let i = 0; i < 80; i++) {
    const snow = document.createElement('div');
    snow.textContent = '❄';
    snow.style.position = 'fixed';
    snow.style.top = '-10px';
    snow.style.left = Math.random() * 100 + 'vw';
    snow.style.fontSize = 10 + Math.random() * 20 + 'px';
    snow.style.opacity = '0.8';
    snow.style.pointerEvents = 'none';

    const duration = 5 + Math.random() * 10;
    snow.style.animation = `fall ${duration}s linear infinite`;

    document.body.appendChild(snow);
}


const style = document.createElement('style');
style.innerHTML = `
@keyframes fall {
    to {
        transform: translateY(110vh) rotate(360deg);
    }
}`;
document.head.appendChild(style);

const btn = document.getElementById('creditsBtn');
const credits = document.getElementById('credits');

btn.addEventListener('click', () => {
    credits.style.display =
        credits.style.display === 'flex' ? 'none' : 'flex';
});